openapi: 3.0.0
info:
  title: API de Gerenciamento de Salas e Usuários
  description: API para criação, participação, mensagens em salas e gerenciamento de usuários.
  version: 1.0.0

paths:
  /register:
    post:
      summary: Registro de usuário
      description: Endpoint para registrar um novo usuário.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  example: "João Silva"
                email:
                  type: string
                  format: email
                  example: "joao.silva@email.com"
                password:
                  type: string
                  example: "senha123"
      responses:
        '200':
          description: Usuário registrado com sucesso.
        '400':
          description: Erro no registro.

  /login:
    post:
      summary: Login de usuário
      description: Endpoint para login de um usuário registrado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: "joao.silva@email.com"
                password:
                  type: string
                  example: "senha123"
      responses:
        '200':
          description: Login realizado com sucesso.
        '400':
          description: Erro no login.

  /:
    post:
      summary: Criar nova sala
      description: Endpoint para criar uma nova sala.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - capacity
              properties:
                name:
                  type: string
                  example: "Sala de Reunião"
                description:
                  type: string
                  example: "Sala para reuniões empresariais"
                capacity:
                  type: integer
                  example: 10
      responses:
        '200':
          description: Sala criada com sucesso.
        '400':
          description: Erro ao criar a sala.

    get:
      summary: Listar todas as salas
      description: Endpoint para listar todas as salas disponíveis.
      responses:
        '200':
          description: Lista de salas.
        '400':
          description: Erro ao listar as salas.

  /join:
    post:
      summary: Participar de uma sala
      description: Endpoint para um usuário entrar em uma sala.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - roomId
              properties:
                roomId:
                  type: string
                  example: "607c1f77bcf86cd799439011"
      responses:
        '200':
          description: Usuário entrou na sala.
        '400':
          description: Erro ao participar da sala.
        '404':
          description: Sala não encontrada.

  /{roomId}/participants:
    get:
      summary: Listar participantes de uma sala
      description: Endpoint para listar todos os participantes de uma sala.
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          example: "607c1f77bcf86cd799439011"
      responses:
        '200':
          description: Lista de participantes da sala.
        '404':
          description: Sala não encontrada.

    delete:
      summary: Remover participante de uma sala
      description: Endpoint para remover um participante de uma sala.
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          example: "607c1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                  example: "609c1e77bcf96cd789439012"
      responses:
        '200':
          description: Participante removido com sucesso.
        '404':
          description: Sala ou participante não encontrado.

  /{roomId}:
    delete:
      summary: Excluir uma sala
      description: Endpoint para excluir uma sala.
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          example: "607c1f77bcf86cd799439011"
      responses:
        '200':
          description: Sala excluída com sucesso.
        '404':
          description: Sala não encontrada.

  /{roomId}/messages:
    get:
      summary: Listar mensagens de uma sala
      description: Endpoint para listar todas as mensagens de uma sala.
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          example: "607c1f77bcf86cd799439011"
      responses:
        '200':
          description: Lista de mensagens da sala.
        '404':
          description: Sala não encontrada.

    post:
      summary: Enviar uma mensagem para a sala
      description: Endpoint para enviar uma mensagem para uma sala.
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          example: "607c1f77bcf86cd799439011"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  example: "Olá, pessoal!"
      responses:
        '200':
          description: Mensagem enviada com sucesso.
        '404':
          description: Sala não encontrada.

  /users/{userId}:
    delete:
      summary: Excluir um usuário
      description: Endpoint para excluir um usuário autenticado.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          example: "609c1e77bcf96cd789439012"
      responses:
        '200':
          description: Usuário excluído com sucesso.
        '403':
          description: Não autorizado a excluir o usuário.
        '404':
          description: Usuário não encontrado.

  /users:
    get:
      summary: Listar todos os usuários (Apenas administradores)
      description: Endpoint para listar todos os usuários cadastrados (somente administradores).
      responses:
        '200':
          description: Lista de usuários.
        '500':
          description: Erro ao listar os usuários.
